export const SAVE_BUSSTOP = 'SAVE_BUSSTOP';

export const REMOVE_BUSSTOP = 'REMOVE_BUSSTOP';

export const SAVE_CURRENT_BUSSTOP = 'SAVE_CURRENT_BUSSTOP';

export const CURRENT_PAGE = 'CURRENT_PAGE';

export const INVALID_BUSSTOP = 'INVALID_BUSSTOP';

export const FAILEDTOSAVE_CURRENT_BUSSTOP = 'FAILEDTOSAVE_CURRENT_BUSSTOP';
